using App.Membership.Infrastructure.Messages;
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Membership.Repositories.Abstract
{
    public interface IRepository<T, TId>
    {
        ValueResponse<T> Add(T entity);

        ValueResponse<T> Update(T entity);
         
        ValueResponse<T> Delete(TId id);

        ValueResponse<T> FindBy(TId id);  
    }
}

