//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using App.Membership.Domain;
using App.Membership.Infrastructure.Messages;

namespace App.Membership.Repositories.Abstract
{
    public interface IUserRepository : IRepository<User, string>
    {
        ResponseBase Lock(string username);

        ValueResponse<bool> ChangePassword(string username, string oldPassword, string newPassword);

        ValueResponse<bool> ValidateUser(string username, string password);

        ListResponse<User> GetAllUsers(int pageIndex, int pageSize, out int totalRecords);

        ValueResponse<bool> IsNewDatabase();

        ResponseBase DeleteUsersForTest();
    }
}

